# Change these first
owner: finbalanced # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: finbalanced Website
    url: https://finbalanced.com
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"
  - name: Backend
    url: https://backend.finbalanced.com/api/health/live
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"
  - name: Stage-Backend
    url: https://stage.backend.finbalanced.com/api/health/live
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"
  - name: Stage-Backend Integrations
    url: https://stage.backend.finbalanced.com/api/health/integrations
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"
  - name: Content-Management-System
    url: https://cms.finbalanced.com/_health
    method: HEAD
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"
  - name: Typesense Search Service
    url: https://p4glf3q790ehnd6tp-1.a1.typesense.net/health
    method: GET
    headers:
    - "User-Agent: $UPTIME_REQUEST_USER_AGENT"


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.finbalanced.com
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/RmzChz8.png
  name: finbalanced
  introTitle: "**finbalanced** is the platform for financial well-being"
  introMessage: This page monitors and informs the status of finbalanced
  themeUrl: https://finbalanced.com/statuspage-theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://finbalanced.com

assignees: # Users to assign downtime issues (optional)
  - BerniWittmann
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
